// get categories
export const GET_CATEGORIES_REQUEST =
  'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS =
  'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL =
  'GET_CATEGORIES_FAIL'

// create category
export const CREATE_CATEGORY_REQUEST =
  'CREATE_CATEGORY_REQUEST'
export const CREATE_CATEGORY_SUCCESS =
  'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAIL =
  'CREATE_CATEGORY_FAIL'

// delete document
export const CATEGORY_DELETE_REQUEST =
  'CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS =
  'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAIL =
  'CATEGORY_DELETE_FAIL'
