// create new collection
export const COLLECTIO_CREATE_REQUEST =
  'COLLECTIO_CREATE_REQUEST'
export const COLLECTIO_CREATE_SUCCESS =
  'COLLECTIO_CREATE_SUCCESS'
export const COLLECTIO_CREATE_FAIL =
  'COLLECTIO_CREATE_FAIL'
export const COLLECTIO_CREATE_RESET =
  'DOCUMENT_CREATE_RESET'

// get collections
export const GET_COLLECTIONS_REQUEST =
  'GET_COLLECTIONS_REQUEST'
export const GET_COLLECTIONS_SUCCESS =
  'GET_COLLECTIONS_SUCCESS'
export const GET_COLLECTIONS_FAIL =
  'GET_COLLECTIONS_FAIL'

// add collection to category
export const ADD_COLL_TO_CATE_REQUEST =
  'ADD_COLL_TO_CATE_REQUEST'
export const ADD_COLL_TO_CATE_SUCCESS =
  'ADD_COLL_TO_CATE_SUCCESS'
export const ADD_COLL_TO_CATE_FAIL =
  'ADD_COLL_TO_CATE_FAIL'

// delete collection
export const COLLECTION_DELETE_REQUEST =
  'COLLECTION_DELETE_REQUEST'
export const COLLECTION_DELETE_SUCCESS =
  'COLLECTION_DELETE_SUCCESS'
export const COLLECTION_DELETE_FAIL =
  'COLLECTION_DELETE_FAIL'
