// fetch documents
export const GET_DOCUMENT_REQUEST =
  'GET_DOCUMENT_REQUEST'
export const GET_DOCUMENT_SUCCESS =
  'GET_DOCUMENT_SUCCESS'
export const GET_DOCUMENT_FAIL = 'GET_DOCUMENT_FAIL'

// fetch single documents
export const GET_SINGLE_DOC_REQUEST =
  'GET_SINGLE_DOC_REQUEST'
export const GET_SINGLE_DOC_SUCCESS =
  'GET_SINGLE_DOC_SUCCESS'
export const GET_SINGLE_DOC_FAIL =
  'GET_SINGLE_DOC_FAIL'

// create document
export const DOCUMENT_CREATE_REQUEST =
  'DOCUMENT_CREATE_REQUEST'
export const DOCUMENT_CREATE_SUCCESS =
  'DOCUMENT_CREATE_SUCCESS'
export const DOCUMENT_CREATE_FAIL =
  'DOCUMENT_CREATE_FAIL'
export const DOCUMENT_CREATE_RESET =
  'DOCUMENT_CREATE_RESET'

// update document
export const DOCUMENT_UPDATE_REQUEST =
  'DOCUMENT_UPDATE_REQUEST'
export const DOCUMENT_UPDATE_SUCCESS =
  'DOCUMENT_UPDATE_SUCCESS'
export const DOCUMENT_UPDATE_FAIL =
  'DOCUMENT_UPDATE_FAIL'

// delete document
export const DOCUMENT_DELETE_REQUEST =
  'DOCUMENT_DELETE_REQUEST'
export const DOCUMENT_DELETE_SUCCESS =
  'DOCUMENT_DELETE_SUCCESS'
export const DOCUMENT_DELETE_FAIL =
  'DOCUMENT_DELETE_FAIL'
